baseURL = "https://tokeinano.com/"
title = "時計奈野"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  description = "時計奈野（Tokei Nano）公式サイト。バーチャルアイドル、J-popアーティスト。"
  image = "/images/hello-world-cover-1440.jpg"

[languages]
  [languages.ja]
    languageCode = "ja-JP"
    languageName = "日本語"
    weight = 1
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 2
  [languages.zh-cn]
    languageCode = "zh-CN"
    languageName = "简体中文"
    weight = 3